---
- name: Tareas por bloques - Validacion formato CRQ o ICR
  block:
    - set_fact:
        idhelix: "{{ idcrqinc | trim }}"
      run_once: true
      delegate_to: localhost

    - name: Validando Formato de Cambio o Incidente
      assert:
        that:
          - idhelix | string | regex_search('(CRQ|INC|REQ)[0-9]{12}')
        fail_msg: "El CRQ, INC o REQ no cumplen con la condiciones del formato"
        success_msg: "El CRQ, INC o REQ cumplen con las condiciones del formato"
      run_once: true
      delegate_to: localhost

- set_fact:
    run_playbook: |
      {% if tarea == 'Crear_VitualBox_Machine' %}
      ['ambientar/vboxvm','mensajes/inicio/vboxvm','crear/vm/vboxvm','crear/clone/vboxvm','crear/disk/vboxvm','crear/net/vboxvm','prender/vboxvm','validar/vboxvm','mensajes/final/vboxvm','api/vboxvm','configurar/nombre/vboxvm']
      {% elif tarea == 'Desconectar_VitualBox_Machine' %}
      ['desconectar/net/vboxvm']
      {% elif tarea == 'Conectar_VitualBox_Machine' %}
      ['ambientar/vboxvm','conectar/vboxvm']
      {% elif tarea == 'Instantanea_VitualBox_Machine' %}
      ['instantanea/vboxvm']
      {% elif tarea == 'Borrar_VitualBox_Machine' %}
      ['borrar/vm/vboxvm']
      {% elif tarea == 'Prueba_VitualBox_Machine' %}
      ['prueba/vboxvm']
      {% else %}
      ['No_selecciono_ninguna_tarea']
      {% endif %}

- name: Select Result
  become: true
  assert:
    that:
      - "'No_selecciono_ninguna_tarea' not in run_playbook"
    fail_msg: "run_playbook"
    success_msg: "Ha seleccionado: {{ run_playbook | replace('\n', '') }}"
  run_once: true
  delegate_to: localhost

- name: Inicia tareas {{ run_playbook }}
  include_tasks: "{{ tareas }}.yml"
  loop: "{{ run_playbook }}"
  loop_control:
    loop_var: tareas

