---
- name: Tasks by blocks - ID Helix format validation
  block:
    - set_fact:
        idhelix: "{{ idcrqinc | trim }}"

    - name: Validando Formato de Cambio o Incidente
      assert:
        that:
          - idhelix | string | regex_search('(CRQ|INC|REQ)[0-9]{12}')
        fail_msg: "El ID Helix no tiene el formato correcto"
        success_msg: "El ID Helix tiene el formato correcto"
  run_once: true
  delegate_to: localhost